spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:java-advanced
    driverClassName: org.h2.Driver
    username: mariabeatriz
    password: 251084
  jpa:
    database:
      platform: org.hibernate.dialect.H2Dialect

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
server:
  port: 8081

debug: true